server:
    port: 4002
    error:
        include-message: always

## h2
# spring:
#     datasource:
#         url: jdbc:h2:mem:user
#     jpa:
#         database-platform: org.hibernate.dialect.H2Dialect
#         hibernate:
#             ddl-auto: update
#     h2:
#         console:
#             enabled: true
#             path: /h2

## mysql
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/app_user
        username: root
        password:
    jpa:
        database-platform: org.hibernate.dialect.MySQL8Dialect
        hibernate:
            ddl-auto: update
        defer-datasource-initialization: true
        open-in-view: false